name: Java CI (JUnit)

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Create directories
        run: mkdir -p out lib test-results

      - name: Download JUnit and Hamcrest
        run: |
          curl -L -o lib/junit-4.13.2.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
          curl -L -o lib/hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      - name: Compile source and test files
        run: |
          bash -c 'javac -cp "lib/*" -d out $(find src -name "*.java") $(find test -name "*.java")'
