name: Java CI (JUnit)

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Create output directory
        run: mkdir -p out

      - name: Compile source and test files
        run: javac -cp "lib/*" -d out $(find src -name "*.java") $(find test -name "*.java")

      - name: Run all JUnit tests
        run: |
          mkdir -p test-results
          for test in $(find test -name '*Test.java' | sed 's|test/||; s|.java$||; s|/|.|g'); do
            echo "Running: $test"
            java -cp "lib/*:out" org.junit.runner.JUnitCore $test || exit 1
          done
